### ISSUE TITLE
Revisar PERFILS de FIRMA en API de Validacio de Firmes

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/pluginsib#14]
Revisa el plugin de validacio de firmes @firma ja que s'han incorporat tipus segons normativa europea:
https://administracionelectronica.gob.es/pae_Home/pae_Actualidad/pae_Noticias/Anio2017/Mayo/Noticia-CTT-2017-05-19-Nuevos-tipos-de-formato-de-firma-en-la-nueva-version-de--firma.html#.WSaDbOsT7ct

**Comment by anadal-fundaciobit** [comment]
Adaptats els tipus que quedaven pendents.
