### ISSUE TITLE
Millorar API Document Custody (Versió 4.0.0)

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/pluginsib#16]
Millorar API Document Custody (Versió 4.0.0). En resum:
              * Locale en les peticions (missatges traduits)     
              * Afegir createDocumentElectronic, updateDocumentElectronic, getDocumentElectronic i supportUpdateDocumentElectronic
              * Eliminar mètodes saveDocument, saveSignature, i revisar familia de de mètodes getDocument*() i getSignature*()
              * Simplificar en un mètodes update i add de metadades
              * Simplificar metadades: Només un valor per clau
              * Afegir getCSV()
              * En signatureCustody afegir perfil de firma
              * Mètodes de Delete metadades ha de passar paràmetre CustodyParameters.
              * Mètodes de Delete metadades han de retornat llista de claus esborrades (no de Metadades)

Aquestes millores estan descrites àmpliament en el document que podeu trobar aquí: https://github.com/GovernIB/pluginsib/blob/pluginsib-1.0/plugins-documentcustody/doc/PropostaApiDocumentCustody_4.0.0.odt

**Comment by cfuster-fundaciobit** [comment]
Aquest tiquet s'ha mogut a: https://github.com/GovernIB/pluginsib-documentcustody/issues/4
