### ISSUE TITLE
Afegir Metadades a MetadataConstants definides  l'Esquema de Metadatos (PAE)

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/pluginsib#18]
Dins la classe MetadataConstants afegir les metadades definides al document que adjunt. Com a mínim les que es refereixen a firmes.

[Esquema_Metadatos_e-EMGDE_2016.pdf](https://github.com/GovernIB/pluginsib/files/1114441/Esquema_Metadatos_e-EMGDE_2016.pdf)

**Comment by cfuster-fundaciobit** [comment]
Aquest tiquet s'ha mogut a: https://github.com/GovernIB/pluginsib-core/issues/5
