### ISSUE TITLE
SCANWEB: Afegir TimeOut a DynamicWebTwain

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/pluginsib#26]
Afegir TimeOut a DynamicWebTwain, ja que en la pàgina principal si no s'espitja cap boto, llavors es queda alla per sempre. Revisar que quan s'envii una petició per saber el document que hi ha en els servidor si retorna cert un error significa un timeout i s'ha de sortir de la pàgina.

**Comment by cfuster-fundaciobit** [comment]
Aquest tiquet s'ha mogut a: https://github.com/GovernIB/pluginsib-scanweb/issues/2
