### ISSUE TITLE
Plugin Doc. Custody Arxiu CAIB: Metadades Opcionals realment són requerides

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/pluginsib#30]
Les Metadades Opcionals addicionals d'Expedient i Document en principi són opcionals, però en el codi font del Plugin estan marcades com requerides i en el cas de que no estiguin definides llavors falla la Custòdia d'aquell document.

**Comment by cfuster-fundaciobit** [comment]
Aquest tiquet s'ha mogut a: https://github.com/GovernIB/pluginsib-documentcustody/issues/3
