### ISSUE TITLE
Afegir tamany de contingut a DocumentContingut i Firma

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/pluginsib#41]
És necessari afegir un atribut "tamany" a les classes es.caib.plugins.arxiu.api.DocumentContingut i es.caib.plugins.arxiu.api.Firma per tal de controlar el tamany en bytes del contingut d'aquestes classes. D'aquesta forma es podrà controlar si l'objecte té contingut i si s'arriba al màxim permès sense haver d'obtenir a priori el contingut.

**Comment by cfuster-fundaciobit** [comment]
Aquest tiquet s'ha mogut a: https://github.com/GovernIB/pluginsib-arxiu/issues/6
