### ISSUE TITLE
Ampliació de tipus de fitxer i extensions

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/pluginsib#44]
S'han afegit CSIG, XSIG i XML com a tipus d'extensió i format per tal de cobrir les necessitats d'enviar documents firmats de certa manera a l'arxiu digital.

**Comment by cfuster-fundaciobit** [comment]
Aquest tiquet s'ha mogut a: https://github.com/GovernIB/pluginsib-arxiu/issues/4
