### ISSUE TITLE
DocCustodyArxiuCAIB: Afegir propietat per ignorar errors al tancarExpedient()

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/pluginsib#53]
Nova propietat [PACKAGE].plugins.documentcustody.arxiudigitalcaib.ignoreerrorwhentancarexpedient 
            (Si val true ignora errors a l'hora de tancar l'expedient) ver. 3.0.13

**Comment by cfuster-fundaciobit** [comment]
Aquest tiquet s'ha mogut a:
https://github.com/GovernIB/pluginsib-documentcustody/issues/2
