### ISSUE TITLE
PLUGIN Validació Firmes XADES i XADES amb "ñ": Error de transformació

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/pluginsib#56]
EN JBOSS Es produeix un error al crear l'XML en XADES des de INTEGRA,  per la qual cosa, la solució sera generar el XMl manualment a partir d'una plantilla FreeMarker:
    
       org.apache.cxf.binding.soap.SoapFault: java.lang.Exception: Error en los parßmetros de entrada.
       

SOLUCIÓ: Generar XML XADES MANUALMENT

**Comment by fbosch-fundaciobit** [comment]
Se m'ha oblidat aferrar els commits de PluginsIB v2. Aqui els teniu:

https://github.com/GovernIB/pluginsib-validatesignature/commit/84b4695e32360720a51c62e7815549f5f5d1ba4d#diff-a8b9fa03b73182b4b56dc897901b6287

**Comment by cfuster-fundaciobit** [comment]
El tiquet s'ha mogut a: https://github.com/GovernIB/pluginsib-validatesignature/issues/7
